/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EFkcjNZA8oq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {Button} from '@/components/ui/button'
import {Separator} from '@/components/ui/separator'
import {Badge} from '@/components/ui/badge'
import {JSX, SVGProps} from 'react'

export function BankStatement() {
  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-8 md:px-6">
      <header className="mb-6 flex items-center justify-between">
        <div className="space-y-1">
          <div className="text-muted-foreground">Account Number</div>
          <div className="font-medium">123456789</div>
        </div>
        <div className="space-y-1 text-right">
          <div className="text-muted-foreground">Available Balance</div>
          <div className="text-2xl font-medium">$12,345.67</div>
        </div>
      </header>
      <div className="space-y-6">
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <Button variant="outline">
              <MoveIcon className="mr-2 h-4 w-4" />
              Transfer
            </Button>
            <Button variant="outline">
              <CreditCardIcon className="mr-2 h-4 w-4" />
              Manage Card
            </Button>
          </div>
          <Separator />
        </div>
        <div className="space-y-4">
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <div className="font-medium">Transactions</div>
              <div className="text-sm text-muted-foreground">Last 30 days</div>
            </div>
            <Separator />
          </div>
          <div className="space-y-2">
            <div className="grid grid-cols-[1fr_3fr_1fr_1fr] items-center gap-4">
              <div className="text-muted-foreground">Date</div>
              <div>Description</div>
              <div className="text-right">Amount</div>
              <div className="text-right">
                <Badge variant="secondary">Pending</Badge>
              </div>
            </div>
            <Separator />
            <div className="grid grid-cols-[1fr_3fr_1fr_1fr] items-center gap-4">
              <div className="text-muted-foreground">Jun 23, 2023</div>
              <div>Acme Inc. - Monthly Subscription</div>
              <div className="text-right text-red-500">-$49.99</div>
              <div className="text-right">
                <Badge variant="secondary">Pending</Badge>
              </div>
            </div>
            <div className="grid grid-cols-[1fr_3fr_1fr_1fr] items-center gap-4">
              <div className="text-muted-foreground">Jun 15, 2023</div>
              <div>Amazon.com - Online Purchase</div>
              <div className="text-right text-red-500">-$79.99</div>
              <div className="text-right">
                <Badge variant="secondary">Completed</Badge>
              </div>
            </div>
            <div className="grid grid-cols-[1fr_3fr_1fr_1fr] items-center gap-4">
              <div className="text-muted-foreground">Jun 10, 2023</div>
              <div>Payroll - Acme Inc.</div>
              <div className="text-right text-green-500">+$2,500.00</div>
              <div className="text-right">
                <Badge variant="secondary">Completed</Badge>
              </div>
            </div>
            <div className="grid grid-cols-[1fr_3fr_1fr_1fr] items-center gap-4">
              <div className="text-muted-foreground">Jun 5, 2023</div>
              <div>Grocery Store - Weekly Shopping</div>
              <div className="text-right text-red-500">-$125.32</div>
              <div className="text-right">
                <Badge variant="secondary">Completed</Badge>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function CreditCardIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}

function MoveIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="5 9 2 12 5 15" />
      <polyline points="9 5 12 2 15 5" />
      <polyline points="15 19 12 22 9 19" />
      <polyline points="19 9 22 12 19 15" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>
  )
}
