/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/afds1lmRu5N
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {Button} from '@/components/ui/button'
import {Textarea} from '@/components/ui/textarea'
import {JSX, SVGProps} from 'react'

export function Redactor() {
  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col rounded-lg bg-background shadow-lg">
      <div className="border-b p-4">
        <h2 className="text-2xl font-bold">Document Redactor</h2>
      </div>
      <div className="flex-1 p-4">
        <div className="relative h-[500px] overflow-auto rounded-md border">
          <div className="absolute inset-0 grid place-items-center bg-white/80 backdrop-blur-sm">
            <div className="grid gap-4">
              <div className="flex items-center gap-2">
                <Button variant="outline" size="sm">
                  <PencilIcon className="h-4 w-4" />
                  Select Text
                </Button>
                <Button variant="outline" size="sm">
                  <SquareIcon className="h-4 w-4" />
                  Draw Box
                </Button>
                <Button variant="outline" size="sm">
                  <HighlighterIcon className="h-4 w-4" />
                  Redact
                </Button>
              </div>
              <Textarea
                className="h-[300px] w-[600px] resize-none rounded-md border p-4"
                defaultValue={`
                  In a land far, far away, there lived a curious young adventurer named Amelia. Amelia had always been fascinated by the mysteries of the world, and she longed to explore the unknown. One day, while wandering through a dense forest, she stumbled upon an ancient ruin hidden deep within the trees.

                  As Amelia approached the crumbling structure, she couldn't help but feel a sense of excitement and trepidation. What secrets did this place hold? Cautiously, she stepped inside, her eyes adjusting to the dim light.

                  To her amazement, the ruin was filled with intricate carvings and hieroglyphics, hinting at a long-forgotten civilization. Amelia spent hours meticulously documenting her findings, her mind racing with theories and hypotheses.

                  Just as she was about to leave, Amelia noticed a hidden passageway in the corner of the room. Without hesitation, she followed the winding corridor, her heart pounding with anticipation. What she discovered next would change the course of her life forever...
                `}
              />
              <Button className="justify-self-end">
                Save Redacted Document
              </Button>
            </div>
          </div>
          <div className="prose max-w-none p-4">
            In a land far, far away, there lived a curious young adventurer
            named Amelia. Amelia had always been fascinated by the mysteries of
            the world, and she longed to explore the unknown. One day, while
            wandering through a dense forest, she stumbled upon an ancient ruin
            hidden deep within the trees. As Amelia approached the crumbling
            structure, she couldn t help but feel a sense of excitement and
            trepidation. What secrets did this place hold? Cautiously, she
            stepped inside, her eyes adjusting to the dim light. To her
            amazement, the ruin was filled with intricate carvings and
            hieroglyphics, hinting at a long-forgotten civilization. Amelia
            spent hours meticulously documenting her findings, her mind racing
            with theories and hypotheses. Just as she was about to leave, Amelia
            noticed a hidden passageway in the corner of the room. Without
            hesitation, she followed the winding corridor, her heart pounding
            with anticipation. What she discovered next would change the course
            of her life forever...
          </div>
        </div>
      </div>
    </div>
  )
}

function HighlighterIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 11-6 6v3h9l3-3" />
      <path d="m22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4" />
    </svg>
  )
}

function PencilIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}

function SquareIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}
